/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s302;

import java.util.HashMap;

public class App {
    public static void main(String[] args) {
		//Borsa
		Agent agentBorsa = new Agent();
		
		//Broker or Agencia
		Agencia IB = new Agencia("InterectiveBrokers", agentBorsa);        
		Agencia BBVA = new Agencia("BBVA", agentBorsa);
		Agencia AB = new Agencia("MyInvestor", agentBorsa);
		Agencia DG = new Agencia("DeGiro", agentBorsa);

        //Informara a tots els agents de tots els valor
        System.out.println("-------------------------");
		agentBorsa.setValue("MRNA",143.54);
        System.out.println("-------------------------");
		agentBorsa.setValue("AAPL",137.89);
        System.out.println("-------------------------");
		agentBorsa.setValue("NFLX",195.11);
        System.out.println("-------------------------");
		agentBorsa.setValue("MMM",158.65);
    }
}
